# .github/workflows/build_on_comment.yml
name: Build on Comment

on:
  issue_comment:
    types: [created]

jobs:
  trigger-python-build:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build') }}
    uses: ./.github/workflows/python_build.yml

      - name: Post result as comment
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const status = context.payload.workflow_run.conclusion === 'success' ? 'succeeded ✅' : 'failed ❌';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Build ${status}`
            });