name: Build on Comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: read          # Allow read access to repository contents
  issues: write  
  
jobs:
  trigger-python-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13.0-rc.1"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          echo python requirements installed     

      - name: Run tests
        working-directory: ./backend
        run: |
          python -m coverage run -m unittest test_api.py
          coverage json

      - name: Post comment on issue
        if: ${{ always() }}  # Run this step even if the previous step fails
        run: |
          if [ "${{ steps.build.outcome }}" == "success" ]; then
            comment="Build passed! Merging is allowed."
          else
            comment="Build failed! Please check the errors."
          fi

          # Post the comment using GitHub CLI
          echo "${comment}" | gh pr comment ${{ github.event.issue.number }} --body -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
