name: Build on Comment

on:
  issue_comment:
    types: [created]

jobs:
  trigger-python-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build') }}
    steps:
      - name: Call Python Build Workflow
        uses: ./.github/workflows/python_build.yml