name: Build on Comment

on:
  issue_comment:
    types: [created]

jobs:
  trigger-python-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build') }}
    steps:
      - name: Call Python Build Workflow
        uses: ./.github/workflows/python_build.yml

      - name: Post result as comment
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const status = github.context.payload.comment.body.includes('/build') ? 'succeeded ✅' : 'failed ❌';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Build ${status}`
            });